### ISSUE TITLE
Arch Linux package

### ISSUE THREAD

**Issue by the9ull** [spesmilo/sx#109]
The Arch Linux aur package doesn't exist anymore

**Comment by veox** [comment]
It's been decided that pushing packages from AUR into the repos is an unneeded overhead.

**Comment by veox** [comment]
To clarify, the past package maintainer, atweiden, has [libbitcoin-explorer](https://aur.archlinux.org/packages.php?O=0&L=0&C=0&K=libbitcoin-explorer), which has superceded `sx`.
