### ISSUE TITLE
Breaking change from secp256k1

### ISSUE THREAD

**Issue by evoskuil** [spesmilo/sx#96]
`bitcoin/secp256k1` is pre-release and sometimes introduces API changes without notice. As such sx should be built against a fork (such as `libbitcoin/secp256k1`) that is compatible with `libbitcoin/libbitcoin`. Currently the install script will break because of this issue.

See also: https://github.com/libbitcoin/libbitcoin/issues/164

**Comment by PabloCastellano** [comment]
May I close this issue then? It seems fixed by using our own fork.
